saba:
  appconfig:
    user: admin
    password: admin
    servers:
      server1:
        host: eureka1
        port: 8761
    KEY_STORE_FILE: saba-jwt.jks
    KEY_STORE_PASSWORD: saba-pass
    KEY_ALIAS: saba-oauth-jwt
    JWK_KID: saba-key-id

---

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:      
      defaultZone: >-
        http://${saba.appconfig.user}:${saba.appconfig.password}@${saba.appconfig.servers.server1.host}:${saba.appconfig.servers.server1.port}/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    
---
    
logging:
  level: 
    org.springframework.security: DEBUG  

---

server:
  port: 0
  servlet:
    context-path: /uaa
spring:
  application:
    name: saba-auth-server
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true 
    show-sql: true    
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true
    username: saba
    password: a+123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: validation
