saba:
  appconfig:
    user: admin
    password: admin
    servers:
      server1:
        host: eureka1
        port: 8761
      product: saba-product-service
      recommendation: saba-product-recommendation-service
      review: saba-product-review-service

---

server:
  port: 8083
spring:
  application:
    name: saba-product-composite-service

---

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:      
      defaultZone: >-
        http://${saba.appconfig.user}:${saba.appconfig.password}@${saba.appconfig.servers.server1.host}:${saba.appconfig.servers.server1.port}/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}