saba:
  appconfig:
    user: admin
    password: admin
    servers:
      server1:
        host: eureka1
        port: 8761
      productCompositeService: saba-product-composite-service

---

server:
  port: 0
spring:
  application:
    name: saba-product-api-service
    
  
---   
      
security:
  oauth2:
    client:  
      client-id: saba-product-api-service
      client-secret: secret123 
    resource:
      id: saba-product-api-service
      token-info-uri: http://localhost:8765/uaa/oauth/check_token
    
---

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:      
      defaultZone: >-
        http://${saba.appconfig.user}:${saba.appconfig.password}@${saba.appconfig.servers.server1.host}:${saba.appconfig.servers.server1.port}/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    
---

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health      
        
---
    
logging:
  level: 
    org.springframework.security: DEBUG       