saba:
  appconfig:
    user: admin
    password: admin
    servers:
      server1:
        host: eureka1
        port: 8761

---

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:      
      defaultZone: >-
        http://${saba.appconfig.user}:${saba.appconfig.password}@${saba.appconfig.servers.server1.host}:${saba.appconfig.servers.server1.port}/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

---

server:
  port: 8765
spring:
  application:
    name: saba-edge-server 
   
---    
     
info:
  component: Zuul Server

zuul:
  routes:
    auth-server-path:
      path: /uaa/**
      serviceId: saba-auth-server  
      stripPrefix: false  
    dashboard-service-path:
      path: /dashboard/**
      serviceId: saba-dashboard-service  
      stripPrefix: false
    api-path:
      path: /api/product-composite/**
      strip-prefix: false
      serviceId: saba-product-composite-service     
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 60000 
    socket-timeout-millis: 60000  
---     

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
